#!/usr/bin/env python3
"""Bold clinical keywords in Marino ICU chapters."""

import re, os

BASE = "/home/node/.openclaw/workspace/marino_icu/content/marino_icu"

# Keywords to bold (don't double-bold existing **)
CHUNKS = [
    # CH01
    ("CH01_Vascular_Access_Primer.md", [
        ("polyurethane", "**polyurethane**"),
        ("silicone", "**silicone**"),
        ("gauge size", "**gauge size**"),
        ("French size", "**French size**"),
        ("Hagen-Poiseuille", "**Hagen-Poiseuille**"),
        ("peripheral catheters", "**peripheral catheters**"),
        ("short peripheral catheters", "**short peripheral catheters**"),
        ("long peripheral catheters", "**long peripheral catheters**"),
        ("midline catheters", "**midline catheters**"),
        ("PICCs", "**PICCs**"),
        ("central venous catheters", "**central venous catheters**"),
        ("CVCs", "**CVCs**"),
        ("midline catheter", "**midline catheter**"),
        ("peripherally inserted central catheters", "**peripherally inserted central catheters**"),
        ("Peripherally Inserted Central Catheters", "**Peripherally Inserted Central Catheters**"),
        ("Central Venous Catheters", "**Central Venous Catheters**"),
        ("Seldinger", "**Seldinger**"),
        ("ultrasound guidance", "**ultrasound guidance**"),
        ("intraosseous", "**intraosseous**"),
        ("IO", "**IO**"),
        ("fat embolism", "**fat embolism**"),
        ("osteomyelitis", "**osteomyelitis**"),
        ("compartment syndrome", "**compartment syndrome**"),
        ("alteplase", "**alteplase**"),
        ("lidocaine", "**lidocaine**"),
        ("fentanyl", "**fentanyl**"),
    ]),
    # CH02
    ("CH02_Central_Venous_Access.md", [
        ("central venous catheter", "**central venous catheter**"),
        ("Central Venous Catheter", "**Central Venous Catheter**"),
        ("midline catheters", "**midline catheters**"),
        ("PICCs", "**PICCs**"),
        ("chlorhexidine", "**chlorhexidine**"),
        ("ultrasound guidance", "**ultrasound guidance**"),
        ("internal jugular vein", "**internal jugular vein**"),
        ("IJV", "**IJV**"),
        ("subclavian vein", "**subclavian vein**"),
        ("femoral vein", "**femoral vein**"),
        ("Trendelenburg", "**Trendelenburg**"),
        ("carotid artery", "**carotid artery**"),
        ("pneumothorax", "**pneumothorax**"),
        ("air embolism", "**air embolism**"),
        ("carina", "**carina**"),
        ("superior vena cava", "**superior vena cava**"),
        ("right atrium", "**right atrium**"),
        ("cardiac tamponade", "**cardiac tamponade**"),
        ("parienti", "**Parienti**"),
    ]),
    # CH03
    ("CH03_The_Indwelling_Vascular_Catheter.md", [
        ("catheter-related thrombosis", "**catheter-related thrombosis**"),
        ("catheter-related bloodstream infection", "**catheter-related bloodstream infection**"),
        ("catheter-related septicemia", "**catheter-related septicemia**"),
        ("biofilm", "**biofilm**"),
        ("coagulase-negative staphylococci", "**coagulase-negative staphylococci**"),
        ("Staphylococcus aureus", "**Staphylococcus aureus**"),
        ("Enterococcus", "**Enterococcus**"),
        ("Candida", "**Candida**"),
        ("alteplase", "**alteplase**"),
        ("vancomycin", "**vancomycin**"),
        ("daptomycin", "**daptomycin**"),
        ("carbapenem", "**carbapenem**"),
        ("Cefepime", "**Cefepime**"),
        ("Piperacillin-Tazobactam", "**Piperacillin-Tazobactam**"),
        ("echinocandin", "**echinocandin**"),
        ("suppurative thrombophlebitis", "**suppurative thrombophlebitis**"),
        ("endocarditis", "**endocarditis**"),
        ("hemodynamic instability", "**hemodynamic instability**"),
        ("deep vein thrombosis", "**deep vein thrombosis**"),
        ("DVT", "**DVT**"),
        ("superior vena cava syndrome", "**superior vena cava syndrome**"),
        ("cardiac tamponade", "**cardiac tamponade**"),
        ("pericardiocentesis", "**pericardiocentesis**"),
    ]),
    # CH04
    ("CH04_Alimentary_Prophylaxis.md", [
        ("dysbiosis", "**dysbiosis**"),
        ("translocation", "**translocation**"),
        ("multiorgan failure", "**multiorgan failure**"),
        ("gastric acid", "**gastric acid**"),
        ("chlorhexidine", "**chlorhexidine**"),
        ("Selective Oral Decontamination", "**Selective Oral Decontamination**"),
        ("SOD", "**SOD**"),
        ("Selective Digestive Decontamination", "**Selective Digestive Decontamination**"),
        ("SDD", "**SDD**"),
        ("polymyxin", "**polymyxin**"),
        ("tobramycin", "**tobramycin**"),
        ("amphotericin", "**amphotericin**"),
        ("gentamicin", "**gentamicin**"),
        ("colistin", "**colistin**"),
        ("vancomycin", "**vancomycin**"),
        ("probiotics", "**probiotics**"),
        ("Clostridium difficile", "**Clostridium difficile**"),
        ("stress ulcer", "**stress ulcer**"),
        ("H2 blocker", "**H2 blocker**"),
        ("famotidine", "**famotidine**"),
        ("proton pump inhibitor", "**proton pump inhibitor**"),
        ("PPI", "**PPI**"),
        ("pantoprazole", "**pantoprazole**"),
        ("omeprazole", "**omeprazole**"),
        ("sucralfate", "**sucralfate**"),
        ("Clarity", "**Clarity**"),
        ("enteral tube feedings", "**enteral tube feedings**"),
    ]),
    # CH05
    ("CH05_Venous_Thromboprophylaxis.md", [
        ("venous thromboembolism", "**venous thromboembolism**"),
        ("VTE", "**VTE**"),
        ("deep venous thrombosis", "**deep venous thrombosis**"),
        ("DVT", "**DVT**"),
        ("pulmonary embolism", "**pulmonary embolism**"),
        ("unfractionated heparin", "**unfractionated heparin**"),
        ("UFH", "**UFH**"),
        ("Low-Molecular-Weight Heparin", "**Low-Molecular-Weight Heparin**"),
        ("LMWH", "**LMWH**"),
        ("enoxaparin", "**enoxaparin**"),
        ("dalteparin", "**dalteparin**"),
        ("fondaparinux", "**fondaparinux**"),
        ("Direct Oral Anticoagulant", "**Direct Oral Anticoagulant**"),
        ("DOAC", "**DOAC**"),
        ("dabigatran", "**dabigatran**"),
        ("apixaban", "**apixaban**"),
        ("rivaroxaban", "**rivaroxaban**"),
        ("warfarin", "**warfarin**"),
        ("intermittent pneumatic compression", "**intermittent pneumatic compression**"),
        ("IPC", "**IPC**"),
        ("graded compression stocking", "**graded compression stockings**"),
        ("GCS", "**GCS**"),
        ("inferior vena cava", "**inferior vena cava**"),
        ("IVC filter", "**IVC filter**"),
        ("heparin-induced thrombocytopenia", "**heparin-induced thrombocytopenia**"),
        ("HIT", "**HIT**"),
        ("antithrombin III", "**antithrombin III**"),
    ]),
    # CH06
    ("CH06_Analgesia_and_Sedation_in_the_ICU.md", [
        ("opioid", "**opioid**"),
        ("morphine", "**morphine**"),
        ("hydromorphone", "**hydromorphone**"),
        ("fentanyl", "**fentanyl**"),
        ("remifentanil", "**remifentanil**"),
        ("meperidine", "**meperidine**"),
        ("Patient-Controlled Analgesia", "**Patient-Controlled Analgesia**"),
        ("PCA", "**PCA**"),
        ("acetaminophen", "**acetaminophen**"),
        ("ketorolac", "**ketorolac**"),
        ("ketamine", "**ketamine**"),
        ("gabapentin", "**gabapentin**"),
        ("carbamazepine", "**carbamazepine**"),
        ("benzodiazepine", "**benzodiazepine**"),
        ("midazolam", "**midazolam**"),
        ("lorazepam", "**lorazepam**"),
        ("propofol", "**propofol**"),
        ("dexmedetomidine", "**dexmedetomidine**"),
        ("haloperidol", "**haloperidol**"),
        ("propofol infusion syndrome", "**propofol infusion syndrome**"),
        ("Richmond Agitation-Sedation Scale", "**Richmond Agitation-Sedation Scale**"),
        ("RASS", "**RASS**"),
        ("Behavioral Pain Scale", "**Behavioral Pain Scale**"),
        ("delirium", "**delirium**"),
        ("QTc", "**QTc**"),
        ("respiratory depression", "**respiratory depression**"),
    ]),
    # CH07
    ("CH07_Oximetry_and_Capnography.md", [
        ("pulse oximetry", "**pulse oximetry**"),
        ("oximetry", "**oximetry**"),
        ("capnography", "**capnography**"),
        ("oxyhemoglobin", "**oxyhemoglobin**"),
        ("deoxygenated hemoglobin", "**deoxygenated hemoglobin**"),
        ("methemoglobin", "**methemoglobin**"),
        ("carboxyhemoglobin", "**carboxyhemoglobin**"),
        ("SpO2", "**SpO2**"),
        ("SaO2", "**SaO2**"),
        ("SvO2", "**SvO2**"),
        ("ScvO2", "**ScvO2**"),
        ("PETCO2", "**PETCO2**"),
        ("PaCO2", "**PaCO2**"),
        ("CO-oximeter", "**CO-oximeter**"),
        ("mixed venous blood", "**mixed venous blood**"),
    ]),
    # CH08
    ("CH08_The_Pulmonary_Artery_Catheter.md", [
        ("pulmonary artery", "**pulmonary artery**"),
        ("PA catheter", "**PA catheter**"),
        ("wedge pressure", "**wedge pressure**"),
        ("thermodilution", "**thermodilution**"),
        ("cardiac output", "**cardiac output**"),
        ("Central Venous Pressure", "**Central Venous Pressure**"),
        ("CVP", "**CVP**"),
        ("pulmonary artery wedge pressure", "**pulmonary artery wedge pressure**"),
        ("PAWP", "**PAWP**"),
        ("cardiac index", "**cardiac index**"),
        ("CI", "**CI**"),
        ("stroke index", "**stroke index**"),
        ("SI", "**SI**"),
        ("systemic vascular resistance index", "**systemic vascular resistance index**"),
        ("SVRI", "**SVRI**"),
        ("pulmonary vascular resistance index", "**pulmonary vascular resistance index**"),
        ("PVRI", "**PVRI**"),
        ("mixed venous O2 saturation", "**mixed venous O2 saturation**"),
        ("SvO2", "**SvO2**"),
        ("oxygen delivery", "**oxygen delivery**"),
        ("DO2", "**DO2**"),
        ("oxygen uptake", "**oxygen uptake**"),
        ("VO2", "**VO2**"),
        ("oxygen extraction ratio", "**oxygen extraction ratio**"),
        ("O2ER", "**O2ER**"),
        ("body surface area", "**body surface area**"),
        ("BSA", "**BSA**"),
    ]),
    # CH09
    ("CH09_Systemic_Oxygenation.md", [
        ("oxygen delivery", "**oxygen delivery**"),
        ("DO2", "**DO2**"),
        ("oxygen uptake", "**oxygen uptake**"),
        ("VO2", "**VO2**"),
        ("SvO2", "**SvO2**"),
        ("ScvO2", "**ScvO2**"),
        ("SaO2", "**SaO2**"),
        ("CaO2", "**CaO2**"),
        ("CvO2", "**CvO2**"),
        ("oxyhemoglobin dissociation curve", "**oxyhemoglobin dissociation curve**"),
        ("P50", "**P50**"),
        ("lactate", "**lactate**"),
        ("hyperlactatemia", "**hyperlactatemia**"),
        ("pyruvate dehydrogenase", "**pyruvate dehydrogenase**"),
        ("thiamine", "**thiamine**"),
        ("beta-agonist", "**beta-agonist**"),
        ("catecholamine", "**catecholamine**"),
        ("cyanide", "**cyanide**"),
        ("metformin", "**metformin**"),
        ("propofol", "**propofol**"),
        ("propylene glycol", "**propylene glycol**"),
        ("sepsis", "**sepsis**"),
        ("anaerobic", "**anaerobic**"),
        ("aerobic", "**aerobic**"),
        ("oxygen extraction ratio", "**oxygen extraction ratio**"),
        ("O2ER", "**O2ER**"),
    ]),
    # CH10
    ("CH10_Intravenous_Fluids.md", [
        ("crystalloid", "**crystalloid**"),
        ("colloid", "**colloid**"),
        ("normal saline", "**normal saline**"),
        ("Ringer's Lactate", "**Ringer's Lactate**"),
        ("Ringer's Acetate", "**Ringer's Acetate**"),
        ("Normosol", "**Normosol**"),
        ("Plasma-Lyte", "**Plasma-Lyte**"),
        ("hypertonic saline", "**hypertonic saline**"),
        ("dextrose", "**dextrose**"),
        ("albumin", "**albumin**"),
        ("hydroxyethyl starch", "**hydroxyethyl starch**"),
        ("HES", "**HES**"),
        ("hetastarch", "**hetastarch**"),
        ("dextran", "**dextran**"),
        ("colloid osmotic pressure", "**colloid osmotic pressure**"),
        ("COP", "**COP**"),
        ("oncotic pressure", "**oncotic pressure**"),
        ("hyperchloremic metabolic acidosis", "**hyperchloremic metabolic acidosis**"),
        ("acute kidney injury", "**acute kidney injury**"),
        ("5% albumin", "**5% albumin**"),
        ("25% albumin", "**25% albumin**"),
        ("balanced salt solution", "**balanced salt solution**"),
    ]),
]

def process_file(filepath, replacements):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    original = content
    for old, new in replacements:
        # Only replace if not already bolded
        if old.startswith('**'):
            content = content.replace(old, new)
        elif f'**{old}**' not in content:
            content = content.replace(old, new)
    changed = content != original
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    return changed

for filename, replacements in CHUNKS:
    filepath = os.path.join(BASE, filename)
    if os.path.exists(filepath):
        changed = process_file(filepath, replacements)
        print(f"{'UPDATED' if changed else 'SKIPPED'}: {filename}")
    else:
        print(f"MISSING: {filename}")
